name: report
on:
  workflow_run:
    workflows: [build]
    types: [completed]
permissions:
  checks: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Report
        uses: dawidd6/action-download-artifact@v2
        with:
          name: test-results-ubuntu
          path: ubuntu
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Download Test Report
        uses: dawidd6/action-download-artifact@v2
        with:
          name: test-results-windows
          path: windows
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: 'windows/test-reports/*.xml,ubuntu/test-reports/*.xml,'
          fail_on_failure: true
          require_tests: true
          check_name: Integration Tests
